version: '2.1'
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@2.8.1
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: sonlele/geardn-api
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: sonlele/geardn-api
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  commit:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - main
