
version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: sonlele/geardn-api
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: sonlele/geardn-api
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      deploy:
        executor: docker/docker
        steps:
          - add_ssh_keys:
                fingerprints:
                  - "SHA256:FSRJHzpHtfeA044IC8zRXo33qoDehPmaCNpgzd7kzsg"
          - run: ssh -oStrictHostKeyChecking=no circleci@http://54.164.120.11 './deploy.sh'
workflows:
  commit:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - main
      - deploy:
        requires:
          - build-and-push
