name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List all files
        run: ls -R

      - name: Check Docker installation
        run: docker --version

      - name: Debug Docker build
        run: |
          echo "Dockerfile content:"
          cat Dockerfile
          echo "Building image..."
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
